config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources  :posts do
    resources :chats 
  end
  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :chat,       presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :province


  belongs_to :user
  has_many   :chats 

  has_one_attached :image

  validates :title,       presence: true
  validates :content,     presence: true
  validates :image,       presence: true
  validates :province_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/province.rb
class Province < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' },
    { id: 49, name: '国外' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :chats
         
         has_one_attached :image

         mount_uploader :image, ImageUploader

         with_options format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: '英数混合のpasswordを設定してください' } do
          validates :password
        end
      
        validates :nickname, presence: true
        validates :last_name, presence: true
        validates :first_name, presence: true
        validates :profile, presence: true
      
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  


  private
  


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:nickname, :last_name, :first_name, :profile, :image])
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def new
    @chat = Chat.new
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @chats = @post.chats.new(chat_params)
    @chats.save
  end

  private 
  def chat_params
    params.permit(:comment).merge(user_id: current_user.id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  
  def index
    @user = User.all
    @posts = Post.all
  end

  def new
    @post = Post.new
    @user = Post.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post
    @chats = Chat.all
    @chat = Chat.new
  end
  
  def edit
    @post = Post.find(params[:id])
    @user = @post
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      @user = Post.all
      @chat = Chat.new
      render :show
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if current_user.id == post.user.id
      post.destroy
      redirect_to root_path
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :image, :content, :province_id).merge(user_id: current_user.id)
  end

  def chat_params
    params.require(:chat).permit(:comment).merge(post_id: current_user.id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.all
    @post = Post.all
  end

  def edit
    @user = User.all
    user = User.new
    current_user.id == @user
    #if current_user.id == @user
    #else
      #redirect_to root_path
    #end
  end

  def update
    @user = User.find(params[:id])
    if user.update(user_params)
      redirect_to action: :show
    else
      @user = user
      render :edit
    end
  end



  private 
  def user_params
    params.require(:user).permit(:nickname, :email, :password).merge(:user, current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chats/_chat_index.html.erb
<p>chat一覧表示成功この下にチャット一覧</p>
<%# @chats.each do |content| %>
  <%#= comment.comment %>
  <%#= content.user.nickname %>
<%# end %>

app/views/chats/_chat_post.html.erb
<%= form_with model: [@post, @chat], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :comment, placeholder: 'type a message' %>
  </div>
  <%= f.submit '送信' %>
<% end %>
  <p>chatpostの表示成功</p>

app/views/chats/new.html.erb
   <%= render 'chats/chat_post' %>
  <%= render 'chats/chat_index' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TabiJiii</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
    <meta name=”viewport” content=”width=device-width,initial-scale=1.0″>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= render "shared/header" %>
<div class="post__new__main">
<div claas="edit__area">
<%= form_with model: @post, local: true do |f| %>
 <%= f.file_field :image, id:"item-image" %>
<%= f.text_area :title, placeholder:"Title", maxlength:"40" %>
<%= f.text_area :content, placeholder:"" ,rows:"7" ,maxlength:"1000" %>
          <span class="indispensable">今回の旅行先</span>
        <%= f.collection_select(:province_id, Province.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
      <%= f.submit "Post" ,class:"sell-btn" %>
      <%=link_to 'back', root_path, class:"back-btn" %>
  <% end %>
</div>
</div>
<%= render "shared/footer" %>

app/views/posts/index.html.erb
<%= render "shared/header" %>
<div class="main">
  <div class="header__background">


  <%#スライダー実装divタグ%>
   <div class="sliders">
      <%= image_tag 'slider.01.jpg', class:"slider__image"%>
      <%= image_tag 'slider.02.jpg', class:"slider__image"%>
      <%= image_tag 'slider.04.jpg', class:"slider__image"%>
  </div>
    <%#スライダー実装divタグ%>
  </div>


  <div class="index__contents">
   <ul class="images">
   <%#最新投稿が10件まで表示%>
  <% @posts.first(10).each do |post|%>
  <li class="image">
   <%= link_to post_path(post.id)  do %>
  <%= post.title %><br>
  <%= image_tag post.image , class:"item-img" %><br>  
  <% end %>
  <%= l post.created_at %><br>
  <%= post.province.name%><br>
  <%#投稿ユーザーのマイページへ遷移できるようにurlを設置する%>
  <span>Photo By</span><%= post.user.nickname%><br>
  </li>
  <% end %>
    <%#最新投稿が10件まで表示%>
</ul>
  <% if user_signed_in? %>
   <div class="post__button__area">
  <%= link_to new_post_path, class:"post_button" do %>
  <%= image_tag '797_me_h.png', class:"post__button__icon"%>
   </div>
  <% end %>
  <% else %>
  <div class="post__button__area">
  <%= link_to new_user_session_path, class:"post__button__area" do %>
  <div class="post__button"></div>
  <%#= image_tag '', class:"post__button__icon"%>
  <% end %>
  <% end %>


  </div>
  <div class="index__under">
  </div>
</div>
<%= render "shared/footer" %>

app/views/posts/new.html.erb
<%= render "shared/header" %>
<div class="post__new__main">
<div claas="post__area">
<%= form_with model: @post, local: true do |f| %>
 <%= f.file_field :image, id:"item-image" %>
<%= f.text_area :title, placeholder:"Title", maxlength:"40" %>
<%= f.text_area :content, placeholder:"" ,rows:"7" ,maxlength:"1000" %>
<div class="weight-bold-text">
        
          <span class="indispensable">今回の旅行先</span>
        </div>
        <%= f.collection_select(:province_id, Province.all, :id, :name, {}, {class:"select-box", id:"item-prefecture"}) %>
        <div class="sell-btn-contents">
      <%= f.submit "Post" ,class:"sell-btn" %>
      <%=link_to 'back', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>
</div>
<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>
<div class="show__main">
<div class="show__contents__area">
<div class="show__title">
 <%= @post.title %><br>
 </div>
 
 <div class="show__image">
 <%= image_tag @post.image , class:"show__item-img" %><br>
 </div>
 <div class="show__nickname">
 <%= @post.user.nickname %><br>
 </div>
 <%= @post.content%><br>
 <%= @post.province.name %><br>
 <%#コメント一覧表示%>
 <% if current_user.id == @post.user.id && user_signed_in? %>
 <%= link_to "edit", edit_post_path(@post) , method: :get %>
 <%= link_to "delete", post_path(@post), method: :delete %>
  <%= render 'chats/chat_post' %>
  <%= link_to new_post_chat_path(@post.id), class:"post_button" do %>
  <div claas="new__comment__path">コメントする</div>
  <% end %>
 <% else %>
  <%= render 'chats/chat_post' %>
 <% end %>
 <%#=コメント機能%>
   <%= render 'chats/chat_index' %>
 </div>
 </div>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer__main">
<div class="footer">
<div class="footer__name">
TabiJiii ~さあ、最高の旅路へ~
</div>
</div>
</div>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%#= link_to image_tag("furima-logo-color.png", class:"furima-icon"), "/" %>
     <%#= image_tag "search.png", class:"search-icon" %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'TabiJiii', root_path, class: "category-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
      <% if current_user.image.url.present? %>
        <li><div class="icon_image__area"><img src=<%= current_user.image.url %> class = "icon_image"></div></li>
      <% end %>
        <li><%= link_to current_user.nickname, user_path(@user), class: "user-nickname" %></li> 
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
        <li><%= link_to 'Login', new_user_session_path, class: "login" %></li>
        <li><%= link_to 'Join us', new_user_registration_path, class: "sign-up" %></li>
      <% end %> 
    </ul>
  </div>
</header>

app/views/users/edit.html.erb
<%= render "shared/header" %>
<%= form_with model: @user, local: true do |f| %>
    

      <%= f.label :nickname %>
      <%= f.text_field :nickname, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="my__page__main">マイページ</div>
<div class="my__post__area">
<% @post.each do |post| %>
<%= post.title %>
<% end %>
</div>
    <%# if current_user.id == @user_id %>
      <%= link_to "#{current_user.nickname}情報変更",  user_registration_path, method: :patch, class: "item-red-btn" %>
        <p class="or-text">or</p>
      <%= link_to "Delete Account",  user_registration_path, method: :delete, class:"item-destroy", id: "delete-confirmation",onclick: "return deleteCheck()" %>
      <%#else%>
      <div>本人以外</div>
    <%# end %>
<%= render "shared/footer" %>